version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fraud_pg
    environment:
      POSTGRES_DB: fraud_db
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst_pw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  pgdata: